--- #YAML:1.0
name:               Test-HTML-W3C
version:            0.04
abstract:           Perform W3C HTML validation testing
author:
    - victor73@gmail.com
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Builder::Module:  0
    WebService::Validator::HTML::W3C:  0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
